name: Spectate
main: com.Chipmunk9998.Spectate.Spectate
version: 2.0
commands:
    spectate:
        description: Lets you spectate another user
        aliases: [spec]
    control:
        description: Lets you control another user