name: Spectate
main: com.chipmunk9998.spectate.Spectate
version: 2.3
commands:
    spectate:
        description: Lets you spectate another user
        aliases: [spec]
    control:
        description: Lets you control another user